name: Toorbo
version: '1.4.1'
main: net.miarma.toorbo.Toorbo
api-version: '1.21'
authors: [Gallardo7761, elpapuu1333 (Contributor & tester)]
permissions:
    toorbo.command:
        description: Permite al usuario ejecutar comandos de Toorbo
        default: true
    toorbo.command.reload:
        description: Permite al usuario recargar la configuración de Toorbo
        default: op
    toorbo.command.config:
        description: Permite al usuario configurar los módulos de Toorbo
        default: op
    toorbo.command.registerweb:
        description: Permite al usuario registrar una cuenta en la web
        default: true
    toorbo.command.tpa:
        description: Permite al usuario enviar una petición de teletransporte
        default: true
    toorbo.command.tpahere:
        description: Permite al usuario enviar una petición de teletransporte a otro jugador
        default: true
    toorbo.command.tpaccept:
        description: Permite al usuario aceptar una petición de teletransporte
        default: true
    toorbo.command.tpdeny:
        description: Permite al usuario rechazar una petición de teletransporte
        default: true
    toorbo.globalchest:
        description: Permite al usuario abrir el cofre global
        default: true
    toorbo.globalchest.others:
        description: Permite al usuario abrir el cofre global de otro jugador
        default: op
    toorbo.disposal:
        description: Permite al usuario abrir el contenedor de basura
        default: true
    toorbo.disposal.others:
        description: Permite al usuario abrir el contenedor de basura de otro jugador
        default: op
    toorbo.command.sendcoords:
        description: Permite al usuario enviar sus coordenadas a otro jugador
        default: true
    toorbo.command.spawn:
        description: Permite al usuario teletransportarse al punto de spawn
        default: true
    toorbo.command.spawn.others:
        description: Permite al usuario teletransportar a otro jugador al punto de spawn
        default: op
    toorbo.command.lobby:
        description: Permite al usuario teletransportarse al lobby
        default: true
    toorbo.command.lobby.others:
        description: Permite al usuario teletransportar a otro jugador al lobby
        default: op
    toorbo.command.opme:
        description: Permite al usuario hacerse op
        default: op
    toorbo.command.deopme:
        description: Permite al usuario quitarse el op
        default: op
    toorbo.command.specialitem:
        description: Permite al usuario obtener un item especial
        default: op
    toorbo.command.blockworld:
        description: Permite al usuario bloquear un mundo
        default: op
    toorbo.command.home:
        description: Permite al usuario teletransportarse a su casa
        default: true
    toorbo.command.sethome:
        description: Permite al usuario establecer su casa
        default: true
    toorbo.command.recinv:
        description: Permite recuperar tu inventario
        default: true
    toorbo.command.gmc:
        description: Permite al usuario cambiar su modo de juego a creativo
        default: op
    toorbo.command.gms:
        description: Permite al usuario cambiar su modo de juego a supervivencia
        default: op
    toorbo.command.gma:
        description: Permite al usuario cambiar su modo de juego a aventura
        default: op
    toorbo.command.gmsp:
        description: Permite al usuario cambiar su modo de juego a espectador
        default: op
    toorbo.command.vanish:
        description: Permite al usuario volverse invisible
        default: op
    toorbo.command.warp:
        description: Permite al usuario teletransportarse a un warp
        default: true
    toorbo.command.warp.add:
        description: Permite al usuario añadir un warp
        default: true
    toorbo.command.warp.remove:
        description: Permite al usuario eliminar un warp
        default: true
    toorbo.command.spy:
        description: Permite al usuario espiar a otro jugador
        default: op
    toorbo.command.freeze:
        description: Permite al usuario congelar a otro jugador
        default: op
    toorbo.command.heal:
        description: Permite al usuario curarse
        default: true
    toorbo.command.heal.others:
        description: Permite al usuario curar a otro jugador
        default: op
    toorbo.command.launch:
        description: Permite al usuario lanzar a otro jugador
        default: op

    toorbo.events.chatformat:
        description: Permite al usuario usar formatos y colores en los mensajes de chat
        default: true
    toorbo.events.adminchat:
        description: Permite al usuario usar el chat de administración
        default: op
    toorbo.events.mentions:
        description: Permite al usuario usar menciones
        default: true

    toorbo.admin:
        description: Permite al usuario ejecutar comandos de administrador
        default: op
        children:
            toorbo.command.reload: true
            toorbo.command.config: true
            toorbo.command.opme: true
            toorbo.command.deopme: true
            toorbo.command.globalchest.others: true
            toorbo.command.disposal.others: true
            toorbo.command.spawn.others: true
            toorbo.command.lobby.others: true
            toorbo.command.specialitem: true
            toorbo.command.blockworld: true
            toorbo.command.gmc: true
            toorbo.command.gms: true
            toorbo.command.gma: true
            toorbo.command.gmsp: true
            toorbo.command.vanish: true
            toorbo.command.spy: true
            toorbo.command.freeze: true
            toorbo.command.heal: true
            toorbo.command.heal.others: true
            toorbo.command.launch: true
            toorbo.events.adminchat: true
            toorbo.player: true

    toorbo.player:
        description: Permite al usuario ejecutar comandos de jugador
        default: true
        children:
            toorbo.command.tpa: true
            toorbo.command.tpahere: true
            toorbo.command.tpaccept: true
            toorbo.command.tpdeny: true
            toorbo.command.registerweb: true
            toorbo.command.globalchest: true
            toorbo.command.disposal: true
            toorbo.command.sendcoords: true
            toorbo.command.spawn: true
            toorbo.command.lobby: true
            toorbo.command.home: true
            toorbo.command.sethome: true
            toorbo.events.chatformat: true
            toorbo.events.mentions: true
            toorbo.command.recinv: true
            toorbo.command.warp: true
            toorbo.command.warp.add: true
            toorbo.command.warp.remove: true
            toorbo.command.me: true
            toorbo.command.do: true

    toorbo.*:
        description: Permite al usuario ejecutar todos los comandos de Toorbo
        default: op
        children:
            toorbo.admin: true
            toorbo.player: true