name: MiarmaCore
version: '1.3.3'
main: dev.gallardo.miarmacore.MiarmaCore
api-version: '1.21'
authors: [Gallardo7761, elpapuu1333 (Contributor)]
permissions:
    miarmacore.command:
        description: Permite al usuario ejecutar comandos de MiarmaCore
        default: true
    miarmacore.command.reload:
        description: Permite al usuario recargar la configuración de MiarmaCore
        default: op
    miarmacore.command.config:
        description: Permite al usuario configurar los módulos de MiarmaCore
        default: op
    miarmacore.command.registerweb:
        description: Permite al usuario registrar una cuenta en la web
        default: true
    miarmacore.command.tpa:
        description: Permite al usuario enviar una petición de teletransporte
        default: true
    miarmacore.command.tpahere:
        description: Permite al usuario enviar una petición de teletransporte a otro jugador
        default: true
    miarmacore.command.tpaccept:
        description: Permite al usuario aceptar una petición de teletransporte
        default: true
    miarmacore.command.tpdeny:
        description: Permite al usuario rechazar una petición de teletransporte
        default: true
    miarmacore.globalchest:
        description: Permite al usuario abrir el cofre global
        default: true
    miarmacore.globalchest.others:
        description: Permite al usuario abrir el cofre global de otro jugador
        default: op
    miarmacore.disposal:
        description: Permite al usuario abrir el contenedor de basura
        default: true
    miarmacore.disposal.others:
        description: Permite al usuario abrir el contenedor de basura de otro jugador
        default: op
    miarmacore.command.sendcoords:
        description: Permite al usuario enviar sus coordenadas a otro jugador
        default: true
    miarmacore.command.spawn:
        description: Permite al usuario teletransportarse al punto de spawn
        default: true
    miarmacore.command.lobby:
        description: Permite al usuario teletransportarse al lobby
        default: true
    miarmacore.command.opme:
        description: Permite al usuario hacerse op
        default: op
    miarmacore.command.deopme:
        description: Permite al usuario quitarse el op
        default: op
    miarmacore.command.specialitem:
        description: Permite al usuario obtener un item especial
        default: op
    miarmacore.command.blockworld:
        description: Permite al usuario bloquear un mundo
        default: op
    miarmacore.command.home:
        description: Permite al usuario teletransportarse a su casa
        default: true
    miarmacore.command.sethome:
        description: Permite al usuario establecer su casa
        default: true

    miarmacore.events.chatformat:
        description: Permite al usuario usar formatos y colores en los mensajes de chat
        default: true
    miarmacore.events.adminchat:
        description: Permite al usuario usar el chat de administración
        default: op
    miarmacore.events.mentions:
        description: Permite al usuario usar menciones
        default: true

    miarmacore.admin:
        description: Permite al usuario ejecutar comandos de administrador
        default: op
        children:
            miarmacore.command.reload: true
            miarmacore.command.config: true
            miarmacore.command.opme: true
            miarmacore.command.deopme: true
            miarmacore.command.globalchest.others: true
            miarmacore.command.disposal.others: true
            miarmacore.command.specialitem: true
            miarmacore.command.blockworld: true
            miarmacore.player: true

    miarmacore.player:
        description: Permite al usuario ejecutar comandos de jugador
        default: true
        children:
            miarmacore.command.tpa: true
            miarmacore.command.tpahere: true
            miarmacore.command.tpaccept: true
            miarmacore.command.tpdeny: true
            miarmacore.command.registerweb: true
            miarmacore.command.globalchest: true
            miarmacore.command.disposal: true
            miarmacore.command.sendcoords: true
            miarmacore.command.spawn: true
            miarmacore.command.lobby: true
            miarmacore.command.home: true
            miarmacore.command.sethome: true
            miarmacore.events.chatformat: true
            miarmacore.events.adminchat: true
            miarmacore.events.mentions: true

    miarmacore.*:
        description: Permite al usuario ejecutar todos los comandos de MiarmaCore
        default: op
        children:
            miarmacore.admin: true
            miarmacore.player: true